name: google_play
description: "Making a Google Play clone."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # data:
  provider: ^6.1.5+1
  http: ^1.6.0
  json_annotation: ^4.9.0
  faker: ^2.2.0
  # fonts:
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
  # images
  - assets/images/verify.png

  ## banners
  - assets/images/banners/banner1.png
  - assets/images/banners/banner2.png
  - assets/images/banners/banner3.png
  - assets/images/banners/banner4.png
  - assets/images/banners/banner5.png
  - assets/images/banners/banner6.png
  - assets/images/banners/banner7.png
  - assets/images/banners/banner8.png

  ## logo
  - assets/images/logo.png

  # icons
  - assets/icons/gamepad.png
  - assets/icons/gamepad_outlined.png
  - assets/icons/app.png
  - assets/icons/app_outlined.png

  # data
  - assets/data/apps.json
  - assets/data/books.json
  - assets/data/games.json